source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'swiftweibo' do
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyRSA'
  #pod 'Heimdall', '~> 1.0.0'
  pod 'AlamofireObjectMapper', '~> 3.0'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end

